language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "bmaggi-github"
    token:
      secure: "7b110dd962c8cd67d1dfeda36e879fbf9c6f680c"

jdk:
  - oraclejdk8

# GUI is required for eclipse testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
